### PR TITLE
Prepare testdata for "apko on top of base image"

### PR DESCRIPTION
**Pull request by sfc-gh-mhazy**
**Overview**

* Added more packages and split them into 2 repositories to simulate one being private. 
* Prepared base image that uses packages from both repositories
* Refreshed preexisting testdata. 

**Context**

https://github.com/chainguard-dev/apko/issues/806

The package dependency graph is the following
```
(repo 1)  baselayout <---- replayout
              ^
              |
(repo 2)  package-x  <---- package-y
```
The base image apko build declares package-y, so after resolving, image contains package-y, package-x and baselayout

In the future the "top" image will be on top of base and will add replayout. 

**Commands for testdata generation**

In `base_packages` directory:

`melange build package-y.melange.yaml --signing-key=private_pkg_key.rsa`
`melange build package-x.melange.yaml --signing-key=private_pkg_key.rsa`

In `testdata` directory:

` apko build base_image.apko.yaml golden:latest base_image/   `

### CODE REVIEW

**Comment by sfc-gh-mhazy** [comment]
@imjasonh could you PTAL? I thought it might be useful to get this separately so that testdata is unchanged in future PR -> we have guarantee new feature doesn't break regular apko builds.

**Comment by sfc-gh-mhazy** [comment]
@sfc-gh-ptabor

**Review by sfc-gh-ptabor — APPROVED** [review]
Please add (at least in the PR description) the list of commands you used to refresh/update the testdata.

**Comment by sfc-gh-mhazy** [comment]
Ok, I have no idea how I ended up in this state of the PR, I will just create a new one...

**Comment by sfc-gh-mhazy** [comment]
Moved to https://github.com/chainguard-dev/apko/pull/1076, previously I had some issues with existing packages but looks like I don't need to change them anymore.

**Pull request closed without merging**
