### PR TITLE
latest go-apk with consistent file ordering

### PR DESCRIPTION
**Pull request by deitch**
@mattmoor had found that the file ordering from `go-apk` was not consistent, which led to differing sha256 sums of the layer.tgz. This fixes that.

In my tests, every time I built any image, I got the exact same contents in the tar, right down to sha256sum of each.

Note that the output tar itself is _not_ consistent, despite the consistent contents. This could be for various reasons, and should be resolved separately.

### CODE REVIEW

**Comment by deitch** [comment]
Once this is in, we should rebase https://github.com/chainguard-dev/apko/pull/668 to it and see that it passes, then merge that in.

**Review by kaniini — APPROVED** [review]

**Comment by deitch** [comment]
This has a race condition. Fix is in https://github.com/chainguard-dev/go-apk/pull/30 . Wait for that to be merged in, I will update this, then this should be clear.

**Comment by deitch** [comment]
Updated now that https://github.com/chainguard-dev/go-apk/pull/30 is in with that commit.

Also made sure that the test that was getting stuck, sails through. There might be more, but that is why we have CI!

**Comment by mattmoor** [comment]
awesome, I'll rebase my other pr 🙏

**Pull request merged**
