### PR TITLE
Drop cloud keychains

### PR DESCRIPTION
**Pull request by jonjohnsonjr**
I don't think we really take advantage of these anywhere. It seems wasteful to carry around these deps.

### CODE REVIEW

**Comment by jonjohnsonjr** [comment]
Opening this as a draft because it seems maybe contentious, but I think it is terrible.

**Review by imjasonh — APPROVED** [review]
We can add them back if anybody ever asks for support.

**Comment by imjasonh** [comment]
Needs a rebase, still lgtm

**Comment by cpanato** [comment]
@jonjohnsonjr is this still required?

**Comment by jonjohnsonjr** [comment]
Rebased.

**Pull request merged**
