### PR TITLE
Bump go-apk

### PR DESCRIPTION
**Pull request by jonjohnsonjr**

### CODE REVIEW

**Comment by jonjohnsonjr** [comment]
I used `errors.Join` like a fool, so I had to bump to 1.20, which seems fine to me but I'm open to pushback.

**Review by kaniini — APPROVED** [review]

**Comment by kaniini** [comment]
Looks fine but the tests are failing in CI.

**Comment by jonjohnsonjr** [comment]
> Looks fine but the tests are failing in CI.

Exposed a race, fixed.

**Review by kaniini — APPROVED** [review]

**Comment by jonjohnsonjr** [comment]
Linter is failing to install itself, hoping to fix that by just bumping to the latest version of that.

**Comment by jonjohnsonjr** [comment]
```

**Comment by jonjohnsonjr** [comment]
Hallelujah.

**Pull request merged**
