### PR TITLE
add annotations to indexes, separate repo and revision annotations, document

### PR DESCRIPTION
**Pull request by imjasonh**
Fixes https://github.com/chainguard-dev/apko/issues/352

### CODE REVIEW

**Comment by kaniini** [comment]
It looks fine to me, but the splitting the VCS URL seems wrong.  Going to wait to see what @puerco says.

**Comment by imjasonh** [comment]
ping @puerco

**Comment by puerco** [comment]
Sorry, I missed this while I was out.

I'm a bit unsure here as we're in OCI territory but I too would prefer to have the VCS URLs be full [SPDX download locator-compatible URLs](https://spdx.github.io/spdx-spec/package-information/#771-description) as it is one piece of data with everything you need in there:

`<vcs_tool>+<transport>://<host_name>[/<path_to_repository>][@<revision_tag_or_branch>][#<sub_path>]`

But perhaps it is not a valid entry in the OCI annotation? I guess it depends on the intended use. Without knowing more context, it seems to me it could work as the spec lists the field as:

> URL to get source code for building the image (string)

(I would add the hash to `.revision` regardless of what we put in `.source`)

**Comment by imjasonh** [comment]
The OCI annotations are specified as:

> - **org.opencontainers.image.source** URL to get source code for building the image (string)
> - **org.opencontainers.image.revision** Source control revision identifier for the packaged software.

This says to me it should be a separate URL and revision.

The vcsurl passed through to the SBOM is still the single SPDX locator, it's only when setting the annotations that they get `strings.Cut` apart.

**Review by kaniini — APPROVED** [review]

**Pull request merged**
