### PR TITLE
Add Docker installation to README installation

### LINKED ISSUE #259: Add docker installed as requirement in README (for MacOS only?)
> AFAIK yes, Docker is needed if you are using the scripts at hack/ to run the dev env, but if you are on Alpine you can probably run it directly. For wider compatibility IMO we should focus on the docker env so yeah this should definitely be added to requirements.

@erikaheidi mentioned this in now closed PR #254. Should docker installation be included in the README in the installation section a prerequisite. Is it only a prerequisite for Mac users?

Once I have an answer, I'm glad to put in a PR.

### PR DESCRIPTION
**Pull request by jspeed-meyers**
Closes #259

Is this helpful? If not, should there be something else? Or should I simply close this issue and PR?

### CODE REVIEW

**Comment by kaniini** [comment]
In general, the hack scripts are replaced by `ghcr.io/distroless/apko:latest`, which does require Docker to run :)

I would recommend mentioning that instead of what is there presently, as its obsolete information now.

**Comment by jspeed-meyers** [comment]
That sounds good. I'm afraid I'll dork up the best way to explain this, so I've unassigned myself and will late someone more familiar with the project or documentation to make this change.

**Comment by amouat** [comment]
I added instructions to use the new Docker image in #311, which I think replaces this.

**Comment by jdolitsky** [comment]
closing as old/inactive. please re-open if necessary

**Pull request closed without merging**
