### PR TITLE
Move default remote options out of library

### PR DESCRIPTION
**Pull request by jonjohnsonjr**
This is causing melange to pull in a bunch of deps it doesn't need.

### CODE REVIEW

**Comment by jonjohnsonjr** [comment]
If we bump this dep in melange after this change:

```diff
diff --git a/go.mod b/go.mod
index d8d768a..ed50e1d 100644
--- a/go.mod
+++ b/go.mod
@@ -41,15 +41,6 @@ require (
        cloud.google.com/go/compute v1.19.3 // indirect
        cloud.google.com/go/compute/metadata v0.2.3 // indirect
        cloud.google.com/go/iam v0.13.0 // indirect
-       github.com/Azure/azure-sdk-for-go v68.0.0+incompatible // indirect
-       github.com/Azure/go-autorest v14.2.0+incompatible // indirect
-       github.com/Azure/go-autorest/autorest v0.11.29 // indirect
-       github.com/Azure/go-autorest/autorest/adal v0.9.23 // indirect
-       github.com/Azure/go-autorest/autorest/azure/auth v0.5.12 // indirect
-       github.com/Azure/go-autorest/autorest/azure/cli v0.4.6 // indirect
-       github.com/Azure/go-autorest/autorest/date v0.3.0 // indirect
-       github.com/Azure/go-autorest/logger v0.2.1 // indirect
-       github.com/Azure/go-autorest/tracing v0.6.0 // indirect
        github.com/MakeNowJust/heredoc v1.0.0 // indirect
        github.com/Microsoft/go-winio v0.6.1 // indirect
        github.com/ProtonMail/go-crypto v0.0.0-20230528122434-6f98819771a1 // indirect
@@ -57,22 +48,6 @@ require (
        github.com/apparentlymart/go-cidr v1.1.0 // indirect
        github.com/asaskevich/govalidator v0.0.0-20230301143203-a9d515a09cc2 // indirect
        github.com/avast/retry-go v3.0.0+incompatible // indirect
-       github.com/aws/aws-sdk-go-v2 v1.18.0 // indirect
-       github.com/aws/aws-sdk-go-v2/config v1.18.25 // indirect
-       github.com/aws/aws-sdk-go-v2/credentials v1.13.24 // indirect
-       github.com/aws/aws-sdk-go-v2/feature/ec2/imds v1.13.3 // indirect
-       github.com/aws/aws-sdk-go-v2/internal/configsources v1.1.33 // indirect
-       github.com/aws/aws-sdk-go-v2/internal/endpoints/v2 v2.4.27 // indirect
-       github.com/aws/aws-sdk-go-v2/internal/ini v1.3.34 // indirect
-       github.com/aws/aws-sdk-go-v2/service/ecr v1.18.11 // indirect
-       github.com/aws/aws-sdk-go-v2/service/ecrpublic v1.16.2 // indirect
-       github.com/aws/aws-sdk-go-v2/service/internal/presigned-url v1.9.27 // indirect
-       github.com/aws/aws-sdk-go-v2/service/sso v1.12.10 // indirect
-       github.com/aws/aws-sdk-go-v2/service/ssooidc v1.14.10 // indirect
-       github.com/aws/aws-sdk-go-v2/service/sts v1.19.0 // indirect
-       github.com/aws/smithy-go v1.13.5 // indirect
-       github.com/awslabs/amazon-ecr-credential-helper/ecr-login v0.0.0-20230519004202-7f2db5bd753e // indirect
-       github.com/chrismellard/docker-credential-acr-env v0.0.0-20230304212654-82a0ddb27589 // indirect
        github.com/cloudflare/circl v1.3.3 // indirect
        github.com/common-nighthawk/go-figure v0.0.0-20210622060536-734e95fb86be // indirect
        github.com/containerd/containerd v1.6.15 // indirect
@@ -80,7 +55,6 @@ require (
        github.com/containers/gvisor-tap-vsock v0.5.0 // indirect
        github.com/cpuguy83/go-md2man/v2 v2.0.2 // indirect
        github.com/davecgh/go-spew v1.1.1 // indirect
-       github.com/dimchansky/utfbom v1.1.1 // indirect
        github.com/docker/cli v24.0.2+incompatible // indirect
        github.com/docker/distribution v2.8.2+incompatible // indirect
        github.com/docker/docker-credential-helpers v0.7.0 // indirect
@@ -103,7 +77,6 @@ require (
        github.com/go-openapi/validate v0.22.1 // indirect
        github.com/goccy/go-yaml v1.9.8 // indirect
        github.com/gogo/protobuf v1.3.2 // indirect
-       github.com/golang-jwt/jwt/v4 v4.5.0 // indirect
        github.com/golang/groupcache v0.0.0-20210331224755-41bb18bfe9da // indirect
        github.com/golang/protobuf v1.5.3 // indirect
        github.com/google/btree v1.1.2 // indirect
@@ -120,7 +93,6 @@ require (
        github.com/insomniacslk/dhcp v0.0.0-20221215072855-de60144f33f8 // indirect
        github.com/jbenet/go-context v0.0.0-20150711004518-d14ea06fba99 // indirect
        github.com/jinzhu/copier v0.3.5 // indirect
-       github.com/jmespath/go-jmespath v0.4.0 // indirect
        github.com/josharian/intern v1.0.0 // indirect
        github.com/josharian/native v1.1.0 // indirect
        github.com/kevinburke/ssh_config v1.2.0 // indirect
@@ -177,3 +149,5 @@ require (
        inet.af/tcpproxy v0.0.0-20221017015627-91f861402626 // indirect
        mvdan.cc/sh/v3 v3.5.1 // indirect
 )
+

**Review by imjasonh — APPROVED** [review]

**Comment by deitch** [comment]
I don't get it. All this seems to do is move some of the configuration out of `oci.go` and into `publish.go`. What does that buy us?

**Comment by imjasonh** [comment]
> I don't get it. All this seems to do is move some of the configuration out of `oci.go` and into `publish.go`. What does that buy us?

Clients that only depend on `pkg/build/oci` don't pick up an implicit dependency on AWS/ACR/GCR cred helpers, which bring in a bunch of cloud client library deps. If those clients want to pass those cred helpers and their deps in, they can, but if they just want to use `authn.DefaultKeychain` which consults `~/.docker/config.json` they can do that too, and avoid a lot of big dependencies.

**Comment by deitch** [comment]
Ah it doesn't change apko, but makes life easier for downstream dependencies. Makes sense.

**Pull request merged**
